Дипломный проект.
AlexKJunior/java-explore-with-me pull request #2
Opened 2023-01-01 13:02 UTC by AlexKJunior

2023-01-02 14:00 UTC, db-exp commented on stats-server/src/main/java/ru/practicum/statistics/StatisticsService.java
> +        for (Hit hit : hits) {
давай попробуем одним запросом получить app, uri, количество, чтобы не ходить на каждый hit в базу

2023-01-08 21:55 UTC, AlexKJunior commented on ewm-service/src/main/java/ru/practicum/ewm/category/model/Category.java
> +    private String name;
Добавил

2023-01-08 21:55 UTC, AlexKJunior commented on ewm-service/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +    private String title;
Добавил

2023-01-08 21:55 UTC, AlexKJunior commented on ewm-service/src/main/java/ru/practicum/ewm/user/model/User.java
> +public class User {
Добавил

2023-01-08 21:56 UTC, AlexKJunior commented on stats-server/src/main/java/ru/practicum/statistics/dao/StatisticDao.java
> +public interface StatisticDao extends JpaRepository<Hit, Long> {
Добавил

2023-01-08 21:56 UTC, AlexKJunior commented on stats-server/src/main/java/ru/practicum/statistics/model/Hit.java
> +public class Hit {
Добавил

2023-01-08 21:56 UTC, AlexKJunior commented on stats-server/src/main/java/ru/practicum/statistics/dao/StatisticDao.java
> +public interface StatisticDao extends JpaRepository<Hit, Long> {
Добавил аннотацию Repository

2023-01-08 21:57 UTC, AlexKJunior commented on checkstyle.xml
> +<!--		<module name="CustomImportOrder">-->
Убрал

2023-01-08 22:03 UTC, AlexKJunior commented on stats-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS hits
Добавил

2023-01-09 08:07 UTC, db-exp requested changes

2023-01-09 08:07 UTC, db-exp commented on stats-server/src/main/java/ru/practicum/statistics/StatisticsService.java
> +        for (Hit hit : hits) {
Не вижу изменений  - можно все uri объединить в массив и одним запросом получить все данные

2023-01-09 08:07 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/ewm/category/CategoryService.java
> +        if (categoryDto.getName() == null && categoryDto.getId() == null) {
не заметил изменений, тут вроде как совсем немного - добавить аннотаций на dto и Valid в контроллер

2023-01-11 21:45 UTC, AlexKJunior commented on ewm-service/src/main/java/ru/practicum/ewm/category/CategoryService.java
> +        if (categoryDto.getName() == null && categoryDto.getId() == null) {
добавил аннотации и Valid  в контроллер

2023-01-11 21:49 UTC, AlexKJunior commented on stats-server/src/main/java/ru/practicum/statistics/StatisticsService.java
> +        for (Hit hit : hits) {
uri объединил в массив. По запросу, я что то торможу с ним, запрос добавлял, но с ним почему то тесты с ошибкой проходили, возможно некорректно записал, вернул пока как было, чтобы без ошибок проходило.

2023-01-12 12:34 UTC, db-exp requested changes

2023-01-12 12:34 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/ewm/compilation/CompilationService.java
> +            throw new ValidationException("Wrong body");
давай добавим в NewCompilationDto аннотации валидации и тогда можно будет убрать отсюда ошибку

2023-01-12 12:34 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/ewm/category/CategoryService.java
> +        if (categoryDto.getName() == null && categoryDto.getId() == null) {
Давай тогда удалим проверки здесь

2023-01-12 14:42 UTC, db-exp requested changes

2023-01-12 14:42 UTC, db-exp commented on stats-server/src/main/java/ru/practicum/statistics/StatisticsService.java
> +                hitCount = statDao.findHitCountByUriWithUniqueIpAndUriIn(hit.getUri());
не совсем так - statDao.findHitCountByUriWithUniqueIpAndUriIn(hit.getUri()); все равно перебираем кучу hit'ов и запрашиваем отдельно. А можно сначала сформировать все uri в список и запросить

2023-01-12 14:42 UTC, db-exp commented on stats-server/src/main/java/ru/practicum/statistics/StatisticsService.java
> +                hitCount = statDao.findHitCountByUriWithUniqueIpAndUriIn(hit.getUri());
как вот тут List<Hit> findAllByTimestampBetweenAndUriIn(LocalDateTime start, LocalDateTime end, String[] uris);

2023-01-12 15:28 UTC, db-exp requested changes

2023-01-12 15:28 UTC, db-exp commented on stats-server/src/main/java/ru/practicum/statistics/StatisticsService.java
> +        for (Hit hit : hits) {
все равно пока в цикле все :)  -  for (Hit hit : hits)

2023-01-15 08:57 UTC, db-exp requested changes
Осталось 3 момента, достаточно быстро поправить

2023-01-15 08:57 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/ewm/client/dto/ViewStats.java
> +    private Long hits;
перебор - NotBlank для строчек, тут можно NotNull

2023-01-15 08:57 UTC, db-exp commented on stats-server/src/main/java/ru/practicum/statistics/dto/ViewStats.java
> +    private Integer hits;
перебор - NotBlank для строчек, тут можно NotNull

2023-01-15 08:57 UTC, db-exp commented on stats-server/src/main/java/ru/practicum/statistics/StatisticsService.java
> +        for (Hit hit : hits) {
и тут поправить - уйти от цикла, решение уже почти готовое, просто надо убрать цикл и проверить, что правильные uris попадают

2023-01-15 17:56 UTC, AlexKJunior commented on stats-server/src/main/java/ru/practicum/statistics/StatisticsService.java
> +        for (Hit hit : hits) {
я поменял, теперь тесты postman не проходят, похоже опять не так записал, посмотри пожалуйста

2023-01-15 17:57 UTC, AlexKJunior commented on ewm-service/src/main/java/ru/practicum/ewm/client/dto/ViewStats.java
> +    private Long hits;
поставил Not Null

2023-01-15 17:58 UTC, AlexKJunior commented on stats-server/src/main/java/ru/practicum/statistics/dto/ViewStats.java
> +    private Integer hits;
поставил NotNull

2023-01-15 18:25 UTC, db-exp commented
как тесты починятся можно присылать - посмотрел правки, молодец

2023-01-17 10:08 UTC, db-exp approved these changes

2023-01-18 12:41 UTC, merged